### ISSUE TITLE
Fix 36 Maintainability, 21 Style issues in BaseTypes\Mediator\reqRespTypes.py

### ISSUE THREAD

**Issue by pattertj** [pattertj/LoopTrader#50]
[CodeFactor](https://www.codefactor.io/repository/github/pattertj/looptrader/overview/main) found multiple issues:

#### Too many instance attributes (9/7)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:149](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L149)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:91](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L91)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:78](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L78)

#### Too many instance attributes (12/7)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:104](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L104)

#### Too many instance attributes (13/7)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:43](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L43)

#### Too many instance attributes (10/7)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:7](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L7)

#### Too few public methods (0/2)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:182](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L182)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:177](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L177)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:170](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L170)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:163](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L163)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:149](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L149)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:144](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L144)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:139](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L139)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:134](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L134)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:127](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L127)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:121](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L121)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:104](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L104)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:91](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L91)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:78](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L78)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:72](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L72)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:36](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L36)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:39](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L39)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:43](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L43)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:26](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L26)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:21](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L21)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:7](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L7)

#### Module name &quot;reqRespTypes&quot; doesn&#39;t conform to snake_case naming style
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:1](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L1)

#### Line too long (184/120)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:156](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L156)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:97](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L97)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:14](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L14)

#### Line too long (152/120)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:82](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L82)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:13](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L13)

#### Line too long (212/120)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:15](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L15)

#### TODO: Change to IN
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:151](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L151)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:110](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L110)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:55](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L55)

#### Missing class docstring
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:182](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L182)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:177](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L177)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:170](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L170)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:163](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L163)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:149](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L149)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:144](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L144)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:139](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L139)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:134](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L134)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:127](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L127)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:121](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L121)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:104](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L104)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:91](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L91)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:78](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L78)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:72](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L72)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:43](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L43)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:39](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L39)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:36](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L36)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:26](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L26)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:21](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L21)
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:7](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L7)

#### Missing module docstring
- [ ]  [BaseTypes\Mediator\reqRespTypes.py:1](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Mediator/reqRespTypes.py#L1)
