### ISSUE TITLE
Fix 25 Maintainability, 20 Style issues in BaseTypes\Strategy\cspByDeltaStrategy.py

### ISSUE THREAD

**Issue by pattertj** [pattertj/LoopTrader#52]
[CodeFactor](https://www.codefactor.io/repository/github/pattertj/looptrader/overview/main) found multiple issues last seen at ee06b1d75d1647ed2d3ad0b84a9167f2f3b3f5a4:

#### Useless return at end of function or method
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:69](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L69)

#### Either all return statements in a function should return an expression, or none of them should.
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:190](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L190)

#### Too many instance attributes (13/7)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:16](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L16)

#### Unnecessary parens after &#39;if&#39; keyword
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:214](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L214)

#### Module name &quot;cspByDeltaStrategy&quot; doesn&#39;t conform to snake_case naming style
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:1](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L1)

#### Line too long (239/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:427](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L427)

#### Line too long (219/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:390](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L390)

#### Line too long (161/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:370](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L370)

#### Line too long (141/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:293](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L293)

#### Line too long (137/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:226](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L226)

#### Line too long (136/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:219](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L219)

#### Line too long (178/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:206](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L206)

#### Line too long (213/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:178](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L178)

#### Line too long (122/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:111](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L111)

#### Line too long (169/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:78](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L78)

#### Line too long (126/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:76](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L76)

#### Line too long (156/120)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:28](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L28)

#### Method could be a function
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:438](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L438)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:370](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L370)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:360](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L360)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:159](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L159)

#### Unused argument &#39;offset&#39;
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:302](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L302)

#### TODO: If positions belongs to this strat...
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:277](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L277)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:259](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L259)

#### # TODO: Check DB if it is our positions
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:175](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L175)

#### Missing function or method docstring
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:438](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L438)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:432](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L432)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:412](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L412)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:390](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L390)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:370](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L370)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:360](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L360)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:350](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L350)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:322](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L322)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:302](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L302)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:266](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L266)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:248](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L248)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:190](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L190)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:159](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L159)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:139](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L139)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:125](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L125)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:98](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L98)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:83](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L83)
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:69](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L69)

#### Missing class docstring
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:16](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L16)

#### Missing module docstring
- [ ]  [BaseTypes\Strategy\cspByDeltaStrategy.py:1](https://www.codefactor.io/repository/github/pattertj/looptrader/source/main/BaseTypes/Strategy/cspByDeltaStrategy.py#L1)
